-- 每日根据callback数据动态更新训练表
INSERT OVERWRITE TABLE callback_datahub_mmoe_v4_training_set PARTITION (p_date = '${bizdate}')
SELECT  
        sq0.request_id
        ,sq1.__identity_id__
        ,sq0.identity_id
        ,sq1.__item_id__
        ,sq0.item_id
        ,sq1.event_scene_id
        ,sq1.day_min
        ,sq1.event_unix_time
        ,sq0.day_h
        ,sq1.is_valid
        ,sq1.is_full
        ,sq1.play_duration
        ,sq0.week_day
        ,sq0.user_type
        ,sq0.terminal_model
        ,sq0.age_group
        ,sq0.gender
        ,sq0.music_vip_type
        ,sq0.used_competitors_last_7d
        ,sq0.user_register_date
        ,sq0.user__cnt_play_30d
        ,sq0.user__cnt_valid_play_30d
        ,sq0.user__cnt_full_play_30d
        ,sq0.user__cnt_collect_30d
        ,sq0.user__cnt_download_30d
        ,sq0.user__cnt_comment_30d
        ,sq0.user__cnt_share_30d
        ,sq0.user__cnt_play_15d
        ,sq0.user__cnt_valid_play_15d
        ,sq0.user__cnt_full_play_15d
        ,sq0.user__cnt_collect_15d
        ,sq0.user__cnt_download_15d
        ,sq0.user__cnt_comment_15d
        ,sq0.user__cnt_share_15d
        ,sq0.user__cnt_play_3d
        ,sq0.user__cnt_valid_play_3d
        ,sq0.user__cnt_full_play_3d
        ,sq0.user__cnt_collect_3d
        ,sq0.user__cnt_download_3d
        ,sq0.user__cnt_comment_3d
        ,sq0.user__cnt_share_3d
        ,sq0.user__cnt_play_music_model_default_30d
        ,sq0.user__cnt_valid_play_music_model_default_30d
        ,sq0.user__cnt_full_play_music_model_default_30d
        ,sq0.user__cnt_play_music_model_default_15d
        ,sq0.user__cnt_valid_play_music_model_default_15d
        ,sq0.user__cnt_full_play_music_model_default_15d
        ,sq0.user__cnt_play_music_model_default_3d
        ,sq0.user__cnt_valid_play_music_model_default_3d
        ,sq0.user__cnt_full_play_music_model_default_3d
        ,sq0.user__num_play_sum_event_value_music_model_default_30d
        ,sq0.user__num_play_sum_event_value_music_model_default_15d
        ,sq0.user__num_play_sum_event_value_music_model_default_3d
        ,sq0.user__num_play_avg_event_value_music_model_default_30d
        ,sq0.user__num_play_avg_event_value_music_model_default_15d
        ,sq0.user__num_play_avg_event_value_music_model_default_3d
        ,sq0.user__kv_num_full_play_song_business_model_sum_event_value_music_model_default_30d
        ,sq0.user__kv_num_full_play_song_business_model_sum_event_value_music_model_default_15d
        ,sq0.user__kv_num_full_play_song_business_model_sum_event_value_music_model_default_3d
        ,sq0.user__kv_item_id_play_music_model_default_30d
        ,sq0.user__kv_singer_id_play_music_model_default_30d
        ,sq0.user__kv_style_tag_id_lv2_play_music_model_default_30d
        ,sq0.user__kv_item_id_valid_play_music_model_default_30d
        ,sq0.user__kv_singer_id_valid_play_music_model_default_30d
        ,sq0.user__kv_style_tag_id_lv2_valid_play_music_model_default_30d
        ,sq0.user__kv_item_id_full_play_music_model_default_30d
        ,sq0.user__kv_singer_id_full_play_music_model_default_30d
        ,sq0.user__kv_style_tag_id_lv2_full_play_music_model_default_30d
        ,sq0.user__kv_item_id_play_music_model_default_15d
        ,sq0.user__kv_singer_id_play_music_model_default_15d
        ,sq0.user__kv_style_tag_id_lv2_play_music_model_default_15d
        ,sq0.user__kv_item_id_valid_play_music_model_default_15d
        ,sq0.user__kv_singer_id_valid_play_music_model_default_15d
        ,sq0.user__kv_style_tag_id_lv2_valid_play_music_model_default_15d
        ,sq0.user__kv_item_id_full_play_music_model_default_15d
        ,sq0.user__kv_singer_id_full_play_music_model_default_15d
        ,sq0.user__kv_style_tag_id_lv2_full_play_music_model_default_15d
        ,sq0.user__kv_item_id_play_music_model_default_3d
        ,sq0.user__kv_singer_id_play_music_model_default_3d
        ,sq0.user__kv_style_tag_id_lv2_play_music_model_default_3d
        ,sq0.user__kv_item_id_valid_play_music_model_default_3d
        ,sq0.user__kv_singer_id_valid_play_music_model_default_3d
        ,sq0.user__kv_style_tag_id_lv2_valid_play_music_model_default_3d
        ,sq0.user__kv_item_id_full_play_music_model_default_3d
        ,sq0.user__kv_singer_id_full_play_music_model_default_3d
        ,sq0.user__kv_style_tag_id_lv2_full_play_music_model_default_3d
        ,sq0.user__kv_item_id_valid_play_30d
        ,sq0.user__kv_style_tag_id_lv2_valid_play_30d
        ,sq0.user__kv_singer_id_valid_play_30d
        ,sq0.user__kv_item_id_full_play_30d
        ,sq0.user__kv_style_tag_id_lv2_full_play_30d
        ,sq0.user__kv_singer_id_full_play_30d
        ,sq0.user__kv_item_id_collect_30d
        ,sq0.user__kv_style_tag_id_lv2_collect_30d
        ,sq0.user__kv_singer_id_collect_30d
        ,sq0.user__kv_item_id_download_30d
        ,sq0.user__kv_style_tag_id_lv2_download_30d
        ,sq0.user__kv_singer_id_download_30d
        ,sq0.user__kv_item_id_share_30d
        ,sq0.user__kv_style_tag_id_lv2_share_30d
        ,sq0.user__kv_singer_id_share_30d
        ,sq0.user__kv_item_id_valid_play_15d
        ,sq0.user__kv_style_tag_id_lv2_valid_play_15d
        ,sq0.user__kv_singer_id_valid_play_15d
        ,sq0.user__kv_item_id_full_play_15d
        ,sq0.user__kv_style_tag_id_lv2_full_play_15d
        ,sq0.user__kv_singer_id_full_play_15d
        ,sq0.user__kv_item_id_collect_15d
        ,sq0.user__kv_style_tag_id_lv2_collect_15d
        ,sq0.user__kv_singer_id_collect_15d
        ,sq0.user__kv_item_id_download_15d
        ,sq0.user__kv_style_tag_id_lv2_download_15d
        ,sq0.user__kv_singer_id_download_15d
        ,sq0.user__kv_item_id_share_15d
        ,sq0.user__kv_style_tag_id_lv2_share_15d
        ,sq0.user__kv_singer_id_share_15d
        ,sq0.user__kv_item_id_valid_play_3d
        ,sq0.user__kv_style_tag_id_lv2_valid_play_3d
        ,sq0.user__kv_singer_id_valid_play_3d
        ,sq0.user__kv_item_id_full_play_3d
        ,sq0.user__kv_style_tag_id_lv2_full_play_3d
        ,sq0.user__kv_singer_id_full_play_3d
        ,sq0.user__kv_item_id_collect_3d
        ,sq0.user__kv_style_tag_id_lv2_collect_3d
        ,sq0.user__kv_singer_id_collect_3d
        ,sq0.user__kv_item_id_download_3d
        ,sq0.user__kv_style_tag_id_lv2_download_3d
        ,sq0.user__kv_singer_id_download_3d
        ,sq0.user__kv_item_id_share_3d
        ,sq0.user__kv_style_tag_id_lv2_share_3d
        ,sq0.user__kv_singer_id_share_3d
        ,sq0.singer_id
        ,sq0.composer
        ,sq0.lyric_writer
        ,sq0.language_tag_id_lv2
        ,sq0.language_tag_id_lv3
        ,sq0.style_tag_id_lv2
        ,sq0.style_tag_id_lv3
        ,sq0.age_tag_id_lv2
        ,sq0.age_tag_id_lv3
        ,sq0.song_business_model
        ,sq0.song_length
        ,sq0.song_name_purified
        ,sq0.item_publish_time
        ,sq0.item__cnt_play_30d
        ,sq0.item__cnt_valid_play_30d
        ,sq0.item__cnt_full_play_30d
        ,sq0.item__cnt_collect_30d
        ,sq0.item__cnt_download_30d
        ,sq0.item__cnt_comment_30d
        ,sq0.item__cnt_share_30d
        ,sq0.item__cnt_play_7d
        ,sq0.item__cnt_valid_play_7d
        ,sq0.item__cnt_full_play_7d
        ,sq0.item__cnt_collect_7d
        ,sq0.item__cnt_download_7d
        ,sq0.item__cnt_comment_7d
        ,sq0.item__cnt_share_7d
        ,sq0.item__cnt_play_3d
        ,sq0.item__cnt_valid_play_3d
        ,sq0.item__cnt_full_play_3d
        ,sq0.item__cnt_collect_3d
        ,sq0.item__cnt_download_3d
        ,sq0.item__cnt_comment_3d
        ,sq0.item__cnt_share_3d
        ,sq0.item__cnt_play_identity_id_30d
        ,sq0.item__cnt_valid_play_identity_id_30d
        ,sq0.item__cnt_full_play_identity_id_30d
        ,sq0.item__cnt_collect_identity_id_30d
        ,sq0.item__cnt_download_identity_id_30d
        ,sq0.item__cnt_comment_identity_id_30d
        ,sq0.item__cnt_share_identity_id_30d
        ,sq0.item__cnt_play_identity_id_7d
        ,sq0.item__cnt_valid_play_identity_id_7d
        ,sq0.item__cnt_full_play_identity_id_7d
        ,sq0.item__cnt_collect_identity_id_7d
        ,sq0.item__cnt_download_identity_id_7d
        ,sq0.item__cnt_comment_identity_id_7d
        ,sq0.item__cnt_share_identity_id_7d
        ,sq0.item__cnt_play_identity_id_3d
        ,sq0.item__cnt_valid_play_identity_id_3d
        ,sq0.item__cnt_full_play_identity_id_3d
        ,sq0.item__cnt_collect_identity_id_3d
        ,sq0.item__cnt_download_identity_id_3d
        ,sq0.item__cnt_comment_identity_id_3d
        ,sq0.item__cnt_share_identity_id_3d
        ,sq0.item__cnt_play_music_model_default_30d
        ,sq0.item__cnt_valid_play_music_model_default_30d
        ,sq0.item__cnt_full_play_music_model_default_30d
        ,sq0.item__cnt_play_music_model_default_7d
        ,sq0.item__cnt_valid_play_music_model_default_7d
        ,sq0.item__cnt_full_play_music_model_default_7d
        ,sq0.item__cnt_play_music_model_default_3d
        ,sq0.item__cnt_valid_play_music_model_default_3d
        ,sq0.item__cnt_full_play_music_model_default_3d
        ,sq0.item__cnt_play_identity_id_music_model_default_30d
        ,sq0.item__cnt_valid_play_identity_id_music_model_default_30d
        ,sq0.item__cnt_full_play_identity_id_music_model_default_30d
        ,sq0.item__cnt_play_identity_id_music_model_default_7d
        ,sq0.item__cnt_valid_play_identity_id_music_model_default_7d
        ,sq0.item__cnt_full_play_identity_id_music_model_default_7d
        ,sq0.item__cnt_play_identity_id_music_model_default_3d
        ,sq0.item__cnt_valid_play_identity_id_music_model_default_3d
        ,sq0.item__cnt_full_play_identity_id_music_model_default_3d
        ,sq0.item__ratio_valid_play_play_music_model_default_30d
        ,sq0.item__ratio_valid_play_play_music_model_default_7d
        ,sq0.item__ratio_valid_play_play_music_model_default_3d
        ,sq0.item__kv_age_group_valid_play_30d
        ,sq0.item__kv_used_competitors_last_7d_valid_play_30d
        ,sq0.item__kv_age_group_full_play_30d
        ,sq0.item__kv_used_competitors_last_7d_full_play_30d
        ,sq0.item__kv_age_group_collect_30d
        ,sq0.item__kv_used_competitors_last_7d_collect_30d
        ,sq0.item__kv_age_group_download_30d
        ,sq0.item__kv_used_competitors_last_7d_download_30d
        ,sq0.item__kv_age_group_comment_30d
        ,sq0.item__kv_used_competitors_last_7d_comment_30d
        ,sq0.item__kv_age_group_share_30d
        ,sq0.item__kv_used_competitors_last_7d_share_30d
        ,sq0.item__kv_age_group_valid_play_7d
        ,sq0.item__kv_used_competitors_last_7d_valid_play_7d
        ,sq0.item__kv_age_group_full_play_7d
        ,sq0.item__kv_used_competitors_last_7d_full_play_7d
        ,sq0.item__kv_age_group_collect_7d
        ,sq0.item__kv_used_competitors_last_7d_collect_7d
        ,sq0.item__kv_age_group_download_7d
        ,sq0.item__kv_used_competitors_last_7d_download_7d
        ,sq0.item__kv_age_group_comment_7d
        ,sq0.item__kv_used_competitors_last_7d_comment_7d
        ,sq0.item__kv_age_group_share_7d
        ,sq0.item__kv_used_competitors_last_7d_share_7d
        ,sq0.item__kv_age_group_valid_play_3d
        ,sq0.item__kv_used_competitors_last_7d_valid_play_3d
        ,sq0.item__kv_age_group_full_play_3d
        ,sq0.item__kv_used_competitors_last_7d_full_play_3d
        ,sq0.item__kv_age_group_collect_3d
        ,sq0.item__kv_used_competitors_last_7d_collect_3d
        ,sq0.item__kv_age_group_download_3d
        ,sq0.item__kv_used_competitors_last_7d_download_3d
        ,sq0.item__kv_age_group_comment_3d
        ,sq0.item__kv_used_competitors_last_7d_comment_3d
        ,sq0.item__kv_age_group_share_3d
        ,sq0.item__kv_used_competitors_last_7d_share_3d
        ,sq0.item__kv_num_play_age_group_sum_event_value_30d
        ,sq0.item__kv_num_valid_play_age_group_sum_event_value_30d
        ,sq0.item__kv_num_full_play_age_group_sum_event_value_30d
        ,sq0.item__kv_num_collect_age_group_sum_event_value_30d
        ,sq0.item__kv_num_play_age_group_sum_event_value_7d
        ,sq0.item__kv_num_valid_play_age_group_sum_event_value_7d
        ,sq0.item__kv_num_full_play_age_group_sum_event_value_7d
        ,sq0.item__kv_num_collect_age_group_sum_event_value_7d
        ,sq0.item__kv_num_play_age_group_sum_event_value_3d
        ,sq0.item__kv_num_valid_play_age_group_sum_event_value_3d
        ,sq0.item__kv_num_full_play_age_group_sum_event_value_3d
        ,sq0.item__kv_num_collect_age_group_sum_event_value_3d
        ,sq0.item__kv_terminal_model_valid_play_30d
        ,REPLACE(sq0.valid_play_100_seq__item_id, CHR(29), ';') AS valid_play_100_seq__item_id
        ,sq0.valid_play_100_seq__style_tag_id_lv2
        ,sq0.valid_play_100_seq__singer_id
        ,sq0.valid_play_100_seq__lyric_writer
        ,sq0.valid_play_100_seq__ts
        ,REPLACE(sq0.full_play_100_seq__item_id, CHR(29), ';') AS full_play_100_seq__item_id
        ,sq0.full_play_100_seq__singer_id
        ,sq0.full_play_100_seq__lyric_writer
        ,sq0.full_play_100_seq__style_tag_id_lv2
        ,sq0.full_play_100_seq__ts
FROM    (
            SELECT  *
            FROM    dws_rec.callback_datahub_ghost_corrected_raw_feat
            WHERE   p_date <= '${bizdate}'
            AND     p_date > '${bizdate_pre3}'
            AND     event_scene_id = 'musicModelDefault'
        ) sq0
INNER JOIN  (
                SELECT  *
                FROM    dws_rec.mmd_mmoe_v1_mmoe_label_table_v2
                WHERE   p_date = '${bizdate}'
                
            ) sq1
ON      sq0.request_id = sq1.request_id
AND     sq0.identity_id = sq1.identity_id
AND     sq0.item_id = sq1.item_id
;